[package]
name = "compiler"
version.workspace = true
edition.workspace = true

[dependencies]
config = { path = "../config" }
runtime = { path = "../runtime" }

ariadne = "0.4.0"
smol_str = { version = "0.2.1", features = ["std"] }
stacker = "0.1.15"
ena = "0.14.2"
libffi = "3.2.0"
serde = { version = "1.0.130", features = ["derive"] }
# chumsky = "1.0.0-alpha.6"
bitmask-enum = "2.2.3"
egg = "0.9.5"

[dev-dependencies]
indoc = "2.0.4"
similar = "2.4.0"
serde_json = "1.0.113"
