[package]
name = "compiler"
version.workspace = true
edition.workspace = true

[features]
default = []
interpret = ["runtime"]

[dependencies]
config = { path = "../config", default-features = false }
runtime = { path = "../runtime", default-features = false, optional = true }

ariadne = { version = "0.4.0" }
smol_str = { version = "0.2.1", features = ["std"] }
# ena = { version = "0.14.2" }
# libffi = { version = "3.2.0" }
serde = { version = "1.0.130", features = ["derive"] }
bitmask-enum = { version = "2.2.3" }

[dev-dependencies]
indoc = "2.0.4"
similar = "2.4.0"
serde_json = "1.0.113"
