[workspace]
members = ["crates/*", "crates/compiler/fuzz"]
exclude = ["crates/tree-sitter-aqua"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
authors = ["Aqua Team"]
readme = "README.md"
