[package]
name = "config"
version.workspace = true
edition.workspace = true

[features]
default = ["clap"]

[dependencies]
clap = { version = "4.5.4", features = ["derive", "string"], optional = true }
