[package]
name = "lang-server"
version.workspace = true
edition.workspace = true

[dependencies]
compiler = { path = "../compiler" }

lsp-server = "0.7.6"
lsp-types = "0.95.0"
serde_json = "1.0.113"
serde = { version = "1.0.113", features = ["derive"] }
