use crate::syntax::source::SourceId;

#[derive(Clone, Copy, Default)]
pub enum Span {
    /// A span that points to a specific range in a source file.
    Source(SourceId, u32, u32),
    /// A span that was generated by the compiler.
    #[default]
    Generated,
}

impl Ord for Span {
    fn cmp(&self, _: &Self) -> std::cmp::Ordering {
        std::cmp::Ordering::Equal
    }
}

impl PartialOrd for Span {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Eq for Span {}

impl PartialEq for Span {
    fn eq(&self, _: &Self) -> bool {
        true
    }
}

impl std::hash::Hash for Span {
    fn hash<H: std::hash::Hasher>(&self, _: &mut H) {}
}

impl std::fmt::Debug for Span {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Span::Source(file, start, end) => write!(f, "{file}:{start}..{end}"),
            Span::Generated => write!(f, "<builtin>"),
        }
    }
}

impl std::fmt::Display for Span {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Span::Source(file, start, end) => write!(f, "{:?}:{}-{}", file, start, end),
            Span::Generated => write!(f, "<builtin>"),
        }
    }
}

impl Span {
    pub fn new(file: SourceId, range: std::ops::Range<u32>) -> Span {
        Span::Source(file, range.start, range.end)
    }

    pub fn file(&self) -> Option<SourceId> {
        match self {
            Span::Source(file, _, _) => Some(*file),
            Span::Generated => None,
        }
    }

    pub fn start(&self) -> Option<u32> {
        match self {
            Span::Source(_, start, _) => Some(*start),
            Span::Generated => None,
        }
    }

    pub fn end(&self) -> Option<u32> {
        match self {
            Span::Source(_, _, end) => Some(*end),
            Span::Generated => None,
        }
    }

    pub fn contains(&self, other: &Span) -> bool {
        if let (Span::Source(f0, start1, end1), Span::Source(f1, start2, end2)) = (self, other) {
            f0 == f1 && start1 <= start2 && end1 >= end2
        } else {
            unreachable!("Should not call `contains` on a generated span")
        }
    }

    pub fn trim(&self, offset: u32) -> Span {
        if let Span::Source(file, start, end) = self {
            Span::Source(*file, start + offset, end - offset)
        } else {
            unreachable!("Should not call `trim` on a generated span")
        }
    }
}

impl std::ops::Add<Span> for Span {
    type Output = Span;

    fn add(self, other: Span) -> Self::Output {
        if let (Span::Source(file, start, _), Span::Source(_, _, end)) = (self, other) {
            Span::new(file, start..end)
        } else {
            unreachable!("Should not call `add` on a generated span")
        }
    }
}

impl std::ops::Add<Option<Span>> for Span {
    type Output = Span;

    fn add(self, other: Option<Span>) -> Self::Output {
        if let Some(other) = other {
            self + other
        } else {
            self
        }
    }
}
